VERSION: 2
VIS_PERIOD: 10

MODEL:
  META_ARCHITECTURE: "MaskDINO"
  WEIGHTS: "https://github.com/IDEA-Research/detrex-storage/releases/download/maskdino-v0.1.0/maskdino_r50_50ep_300q_hid1024_3sd1_instance_maskenhanced_mask46.1ap_box51.5ap.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 0

  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 39
    CONVS_DIM: 256
    COMMON_STRIDE: 4
    NORM: "GN"
    LOSS_WEIGHT: 1.0

    # [MaskDINO] MSDeformAttn encoder config
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3

    # [MaskDINO] pixel decoder config
    MASK_DIM: 256
    TRANSFORMER_ENC_LAYERS: 6
    PIXEL_DECODER_NAME: "MaskDINOEncoder"

  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    STRIDE_IN_1X1: false
    STEM_OUT_CHANNELS: 64

  # [MaskDINO] MaskDINO model config
  MaskDINO:
    # [MaskDINO] loss
    PANO_BOX_LOSS: false
    SEMANTIC_CE_LOSS: false
    DEEP_SUPERVISION: true
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    DICE_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0

    # [MaskDINO] transformer config
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 9
    INITIAL_PRED: true
    PRE_NORM: false
    BOX_LOSS: true
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100

    ENFORCE_INPUT_PROJ: false
    TWO_STAGE: true
    INITIALIZE_BOX_TYPE: "bitmask"
    DN: "seg"
    DN_NOISE_SCALE: 0.4
    DN_NUM: 100

    SIZE_DIVISIBILITY: 32

    # [MaskDINO] transformer module
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"

    # [MaskDINO] point loss config
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75

    # [MaskDINO] MaskDINO inference config
    TEST:
      SEMANTIC_ON: false
      INSTANCE_ON: true
      PANOPTIC_ON: false
      OBJECT_MASK_THRESHOLD: 0.25
      OVERLAP_THRESHOLD: 0.8

INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"

  # data config
  DATASET_MAPPER_NAME: "coco_instance_lsj"

DATASETS:
  TRAIN: ("pano_train",)
  TEST: ("pano_eval",)

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4

SOLVER:
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  MAX_ITER: 1_000_000
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WARMUP_METHOD: "linear"
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 1
  BIAS_LR_FACTOR: 1.0

  CLIP_GRADIENTS:
    ENABLED: true
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0

  AMP:
    ENABLED: false

  # [MaskDINO] solver config
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1

TEST:
  EVAL_PERIOD: 5000
  AUG:
    ENABLED: false
    MIN_SIZES: [512, 768, 1024, 1280, 1536, 1792]
    MAX_SIZE: 4096
    FLIP: true
